Fix topic filter matching
Yakifo/amqtt pull request #28
Opened 2021-03-14 12:43 UTC by lrasku

- re.escape() the whole filter string first to escape _all_ regex
  metacharacters in it, not just $. (# and + are both regex metacharacters,
  so their replace expressions now need a leading \\ to replace the
  escaping, too.)
- # matches topics both with and without a trailing /, so the replace
  expressions adds a '?' before the '.*'. The .lstrip('?') at the end removes
  this in case the # was the first character in the filter.
- + should only match a single level, but it should _also_ match empty levels,
  so use '[^/]*' to replace it.
- Use Regex.fullmatch() to match against the whole topic string, not just
  its start.

Also add two unit tests to test this matching, and fix an incorrect match
against + in test_client_subscribe_publish_dollar_topic_2.

2021-03-14 12:49 UTC, FlorianLudwig commented
Hi @Irasku

thanks for the MR and it does include tests, awesome :)

One question regarding the tests:  Would it be desirable to directly call the `matches()` function and test it's output instead of starting a server and client and do a full end-to-end test? This way the test would not have to rely so much on timeouts.

2021-03-14 13:28 UTC, lrasku commented
Maybe... I would personally feel more confident in the full end-to-end tests, since the matches() function isn't really intended to be part of the broker's public interface. But I see that the extant tests aren't too shy about testing the broker's internals anyway, so if you prefer I can change them to call the function directly.

2021-03-14 20:35 UTC, HerrMuellerluedenscheid requested changes
Thanks for fixing this and special thanks for including a test!

I would also strongly prefer to have atomic tests that only test what has been added without the additional overhead. Atomic tests are more self-explanatory and much easier to understand when they fail. Also, I think that timeouts in tests are rather risky as they _may_ lead to failures which are hard to reproduce and give others a really tricky and time consuming riddle to understand.

2021-03-15 08:44 UTC, lrasku commented
Fixed merge conflicts with latest master and rewrote the unit tests to test the matches() function directly & synchronously

2021-03-15 10:35 UTC, HerrMuellerluedenscheid commented
Can you rebase once more? I accidentally pushed to master (which should have been protected) Sorry for the mess and the extra effort! Thanks for adopting the tests!

2021-03-15 10:35 UTC, HerrMuellerluedenscheid approved these changes
Needs rebase but looks good to go!

2021-03-15 10:41 UTC, lrasku commented
One more rebase

2021-03-15 12:43 UTC, merged