Make WebSockets work with IPv6 addresses
Yakifo/amqtt pull request #30
Opened 2021-03-14 12:51 UTC by lrasku

WebSocketsWriter.get_peer_info() naively returns just
self._protocol.remote_address, but this is a 4-tuple in IPv6,
which will raise ValueErrors when client code tries to unpack
it into two elements. Fortunately the first two elements of the
tuple are the same as in IPv4 and should be all that we need
(get_peer_info() is currently only used for logging), so just
return a 2-prefix of the value instead.

2021-03-14 15:59 UTC, FlorianLudwig commented
Could you add a comment to the code mentioning what you mentioned here?

So it is clear to the reader of the code that the `[:2]` is for IPv6 support.

2021-03-14 19:48 UTC, FlorianLudwig requested changes
Please add code comment

2021-03-15 08:21 UTC, lrasku commented
Added comment explaining what was done

2021-03-15 09:16 UTC, FlorianLudwig approved these changes

2021-03-15 09:16 UTC, merged